[package]
name = "async-graphql-rocket-ws"
description = "Subscription handler for async_graphql and rocket_ws"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7.0.17"
futures = "0.3.31"
rocket_ws = "0.1.1"
